pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'Higress'
   keywords: '官网,首页'
   description: 'Higress官网'
  # home config
  en-us:
   title: 'Higress'
   keywords: 'Official,Higress'
   description: 'Higress Official Website'
 community:
  # 社区页配置
  zh-cn:
   title: '社区'
   keywords: 'Higress,社区'
   description: 'Higress社区'
  # community page config
  en-us:
   title: 'Community'
   keywords: 'Higress,Community'
   description: 'Higress Community'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客'
   keywords: 'Higress,博客'
   description: 'Higress 博客'
  en-us:
   # blog list page config
   title: 'Blog'
   keywords: 'Higress,Blog'
   description: 'Higress Blog'
