site:
  name: Higress
  site: 'https://higress.cn/'
  base: '/'
  trailingSlash: 'always'
  websiteGithubUrl: 'https://github.com/higress-group/higress-group.github.io/blob/develop-astro-higress'
  githubUrl: 'https://github.com/alibaba/higress'
  logoUrl: "https://img.alicdn.com/imgextra/i1/O1CN01aIB6n51zcgTM5vhku_!!6000000006735-2-tps-156-48.png"

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id:
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: e7WQkK
    clarityAlalytics:
      id: l4jzj6wbhh


# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s — Higress'
  description: "Higress - AI Native API 网关，为 AI 应用提供统一的流量管理、安全防护和服务治理能力"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Higress
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image
